name: API Test JEST Playground

on:
  # workflow_dispatch: # manual trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ feat/api-setup ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-html-report
          path: ./test-results/result.html
